### ISSUE TITLE
Error: Resource not accessible by integration

### ISSUE THREAD

**Issue by FaterYU** [ahmadnassri/action-commit-lint#285]
# Error: Resource not accessible by integration
When I use the following `ci.yml` file to start a pull request, it raises some errors.

- the repository is private
- the pull request is from branch `develop` to branch `main`

## ci.yml

```yml
name: Main CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: ahmadnassri/action-commit-lint@v1
        with:
          config: angular
```

## Job errors

![image](https://github.com/ahmadnassri/action-commit-lint/assets/74441262/8929d1c9-a5b7-438e-a551-69b5bce9d23e)

```bash
Run ahmadnassri/action-commit-lint@v1
  with:
    config: angular
    github-token: ***
/usr/bin/docker run --name ghcrioahmadnassriactioncommitlintv1_1a1ff[2](https://github.com/FaterYU/BodyBuddy/actions/runs/6931896487/job/18855462294#step:3:2) --label fbe99[3](https://github.com/FaterYU/BodyBuddy/actions/runs/6931896487/job/18855462294#step:3:3) --workdir /github/workspace --rm -e "INPUT_CONFIG" -e "INPUT_GITHUB-TOKEN" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/BodyBuddy/BodyBuddy":"/github/workspace" ghcr.io/ahmadnassri/action-commit-lint:v1
Error: Resource not accessible by integration
HttpError: Resource not accessible by integration
    at /action/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (node:internal/process/task_queues:9[4](https://github.com/FaterYU/BodyBuddy/actions/runs/6931896487/job/18855462294#step:3:4):[5](https://github.com/FaterYU/BodyBuddy/actions/runs/6931896487/job/18855462294#step:3:6))
    at async main (/action/index.js:42:22)
```

How can I fix it on the pull request?

**Comment by ahmadnassri** [comment]
`v1` is over 2 years old, I realize the docs are old (and will update them now) you should use `v2`
